name: CI

on:
  push:
    branches: 
      - '**'  # Executa em qualquer branch
  pull_request:
    branches: 
      - '**'  # Executa em qualquer branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libgl1-mesa-dev \
          xorg-dev

    - name: Install dependencies
      run: go mod tidy

    - name: Create git patch
      run: |
        if git rev-parse HEAD~1 > /dev/null 2>&1; then
          git diff HEAD~1 HEAD > patch.diff
        else
          echo "No previous commit found, creating empty patch" > patch.diff
        fi
      
    - name: Run golangci-lint
      run: golangci-lint run -c .golangci.yml --new-from-patch patch.diff # Usa o arquivo de patch criado

    - name: Run tests
      run: go test -v ./...
